spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQL94Dialect
      jdbc.lob.non_contextual_creation: true
  jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: ['health', 'info', 'prometheus']

pattern:
  console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

map:
  service:
    debug: false
  scrub-on-bootstrap: true




# run this for heroku
# heroku config:set PARTNER_ACTIVE_PROFILE=uat


################################# DEV ###################################
---
spring:
  profiles: dev
  datasource:
    platform: postgres
    url: jdbc:postgresql://${PARTNER_DB_HOST:localhost}:${PARTNER_DB_PORT:5432}/${PARTNER_DB_NAME:test}
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

# Server
server:
  port: ${PARTNER_SERVER_PORT:8081}




